apiVersion: v1
kind: ConfigMap
metadata:
  name: cloud-provider-config
  namespace: {{ .Release.Namespace }}
data:
  cloudprovider.conf: |
    [Global]
    soap-roundtrip-count = "{{ .Values.soapRoundtripCount }}"
    ip-family = "ipv4"
    {{- if .Values.caFile }}
    ca-file="{{ .Values.caFile }}"
    {{- end }}
    {{- if .Values.caFile }}
    thumbprint="{{ .Values.thumbprint }}"
    {{- end }}

    [VirtualCenter "{{ .Values.serverName }}"]
    port = "{{ .Values.serverPort }}"
    datacenters = "{{ .Values.datacenters }}"
    user = "{{ .Values.username }}"
    password = "{{ .Values.password }}"
    insecure-flag = "{{ .Values.insecureFlag }}"

    [Labels]
    {{- if .Values.labelRegion }}
    region = "{{ .Values.labelRegion }}"
    {{- end }}
    {{- if .Values.labelZone }}
    zone = "{{ .Values.labelZone }}"
    {{- end }}

    [LoadBalancer]
    ipPoolName = "{{ .Values.loadbalancer.ipPoolName }}"
    size = {{ .Values.loadbalancer.size }}
    tier1GatewayPath = "{{ .Values.loadbalancer.tier1GatewayPath }}"
    tcpAppProfileName = "{{ .Values.loadbalancer.tcpAppProfileName }}"
    udpAppProfileName = "{{ .Values.loadbalancer.udpAppProfileName }}"
    tags = { {{ template "tags" .Values.loadbalancer.tags }} }

    {{- range $i, $class := .Values.loadbalancer.classes }}

    [LoadBalancerClass {{ $class.name | quote }}]
    {{- if $class.ipPoolName }}
    ipPoolName="{{ $class.ipPoolName }}"
    {{- end }}
    {{- if $class.tcpAppProfileName }}
    tcpAppProfileName="{{ $class.tcpAppProfileName }}"
    {{- end }}
    {{- if $class.udpAppProfileName }}
    udpAppProfileName="{{ $class.udpAppProfileName }}"
    {{- end }}
    {{- end }}

    [NSX-T]
    user = "{{ .Values.nsxt.username }}"
    password = "{{ .Values.nsxt.password }}"
    {{- if .Values.nsxt.usernameNE }}
    userNE = "{{ .Values.nsxt.usernameNE }}"
    passwordNE = "{{ .Values.nsxt.passwordNE }}"
    {{- end }}
    host = "{{ .Values.nsxt.host }}"
    insecure-flag = "{{ .Values.nsxt.insecureFlag }}"
    remote-auth = "{{ .Values.nsxt.remoteAuth }}"
