---
apiVersion: {{ include "storageclassversion" . }}
kind: StorageClass
metadata:
  name: default-class
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
    resources.gardener.cloud/delete-on-invalid-update: "true"
provisioner: csi.vsphere.vmware.com
volumeBindingMode: WaitForFirstConsumer
parameters:
  storagePolicyName: "{{ .Values.storagePolicyName }}"
